### ISSUE TITLE
Cannot log in, says too may failure attempts from my network, but that's not true.

### ISSUE THREAD

**Issue by AndrewPrzelucki** [GMMan/SteamNotificationsTray#24]
Hello, just tried version 1.1.4.2 and it won't log in, says too many log-in failures from my network. Everything works fine for me, so no reason for such information.

**Comment by GMMan** [comment]
Check what happens when you try to log into Steam Community on an incognito browser window. The program emulates browser login, so if your browser can't do it, it's not going to work in the program either. The error may also show if you're on a shared connection and someone else is trying to log in too much.

**Comment by AndrewPrzelucki** [comment]
I'm on the latest Windows 10 update (I do fresh, clean installs twice a year, when the updates come out), I use Google's Chrome and of course the Steam app. I did an incognito login and it worked fine, quickly logged me in. I am not on a shared network, I connect through my phone on 4G. I have no connection issues.

**Comment by GMMan** [comment]
I tried relogging when you created the issue, so there isn't anything weird with the code. Using tethering does sound like something that could affect things, since the IP address might change more frequently and get pooled with something someone else used. I would suggest just waiting a while; Steam was acting up earlier this week (and still acting up now). (Also see #23, where someone ran into the same thing and was able to log in after waiting.)

**Comment by AndrewPrzelucki** [comment]
OK, thank you for addressing my issue. I'll retry and see.

**Comment by AndrewPrzelucki** [comment]
Finally, it works! My first attempt today failed, but I left your app login window open and tried a bit later. It worked right away.
